### ISSUE TITLE
StFwdTrackMaker doesn't compile in 64-bit

### ISSUE THREAD

**Issue by genevb** [star-bnl/star-sw#139]
setup 64b
stardev
mkdir -p test/StRoot
cd test
cp -R $STAR/StRoot/StFwdTrackMaker ./StRoot/
cons
...
In file included from .sl73_x8664_gcc485/OBJ/StRoot/StFwdTrackMaker/StFwdTrackMaker.cxx:2:0:
StRoot/StFwdTrackMaker/include/Tracker/FwdHit.h:4:26: fatal error: KiTrack/IHit.h: No such file or directory
 #include "KiTrack/IHit.h"
                          ^
compilation terminated.

**Comment by plexoos** [comment]
Here is one solution: Load installed KiTrack package into your environment

```
module use /cvmfs/star.sdcc.bnl.gov/star-spack/spack/share/spack/modules/linux-rhel7-x86_64
module load kitrack-01-10-star-1-gcc-4.8.5-h35oof3
```

**Comment by genevb** [comment]
Hi, Dmitri

> Here is one solution: Load installed KiTrack package into your environment

Our environment is the standard STAR login environment. If you're proposing to change that environment, you need to bring Jerome into the discussion. I assume that changing the environment (should that be the chosen solution) will be either transparent to the Production Team and other users, or you'll let us know what impacts to expect.

Thanks,
-Gene

**Comment by plexoos** [comment]
> you need to bring Jerome into the discussion

@jlauret

> you'll let us know what impacts to expect

The proposed solution adds the kitrack's include path to the CPATH env variable

**Comment by fgeurts** [comment]
Hi, I am reviewing old issues on rainy Sunday afternoon ... this particular issue has not been followed up in ~3years. Is there still a need to leave it open? Please advise.

**Comment by genevb** [comment]
The STAR environment did eventually get modified to include the spack modules. Thanks for the ping, Frank.
