### ISSUE TITLE
Regression tests for the simulation in CI

### ISSUE THREAD

**Issue by veprbl** [star-bnl/star-sw#141]
There is a big chunk of our software that is not exercised in our CI. It would be nice to get some tests for the simulation running.

**Comment by plexoos** [comment]
Working on it... The goal is to run all of these tests: https://github.com/star-bnl/star-sw/blob/main/tests/joblist.json

On a related note, there is a way to extract a small number of events from daq files and I plan to update the `star-test-data` image

**Comment by plexoos** [comment]
All fzd files from [this list](https://github.com/star-bnl/star-sw/blob/main/tests/joblist.json) can be processed during the CI test. See #135
