### ISSUE TITLE
Assert in Y2000 real data nightly tests

### ISSUE THREAD

**Issue by genevb** [star-bnl/star-sw#185]
As reported in the status of DEV nightly test jobs...
https://www.star.bnl.gov/devcgi/weekDEVjobStatus.pl
...Three Y2000 real data tests have been crashing with asserts since 2021-10-29:

...
StiMaker:INFO  - StiMasterHitLoader::loadEvent() - TpcHitLoader loaded 99638 hits
StiDetectorContainer::begin() -I- size:540
root4star: .sl73_gcc485/obj/StRoot/Sti/StiKalmanTrackFinder.cxx:463: void StiKalmanTrackFinder::find(StiKalmanTrack*, int, StiKalmanTrackNode*, StiKalmanTrackFinder::QAFind&): Assertion `mEventPerm>=0 && "FATAL::TOO MANY permutations"' failed.

To reproduce:
root4star -b -q -l 'bfc.C(100,"p2000,VFMinuit,logger,CMuDst,NosvtIT,NossdIT","st_physics_1229021_raw_0003.daq")'

DAQ file is here:
/star/rcf/test/daq/2000/08/st_physics_1229021_raw_0003.daq

-Gene

**Comment by dmarkh** [comment]
Okay, private communications with Yuri revealed that he has switched from "RunLog/magFactor" to "RunLog/onl/starMagOnl" data for TPC calibrations. starMagOnl contains raw STAR magnet current, magFactor contains processed STAR magnet current. For most years these are identical (filled in by online to offline migration at the same time). For earlier years there are differences. Yuri traced this issue to Y2000, where couple dozen entries or so are missing from the starMagOnl table. If no one objects, I will convert existing magFactor entries to starMagOnl for [2000-01-01 - 2001-01-01] period on Monday.

**Comment by dmarkh** [comment]
Okay, 196 rows of "RunLog_onl/starMagOnl" were added - converted from the ScaleFactor entries. dataID range: [ 199173 .. 199339 ], beginTime range [ "2000-06-19 21:18:45" .. "2001-08-03 01:06:37" ]. entryTime was set to the entryTime of ScaleFactor data.

Try now?
