### ISSUE TITLE
Cannot pull base images from star-bnl/packages by latest tag (no matching manifest)

### ISSUE THREAD

**Issue by plexoos** [star-bnl/star-sw#197]
After updating settings in "Packages" > star-sw-root5-base > "Package settings" > "Manage Actions access" to allow pushes in [this workflow ](https://github.com/star-bnl/star-sw/blob/main/.github/workflows/build-containers.yml) the latest tag got overwritten. Pulling the image now results in the following error:

```
$ docker pull ghcr.io/star-bnl/star-sw-root5-base:latest
latest: Pulling from star-bnl/star-sw-root5-base
no matching manifest for linux/amd64 in the manifest list entries
```

The workaround is to pull an image with a specific digest like this:

```
$ docker pull ghcr.io/star-bnl/star-sw-root5-base@sha256:4bed8a8b729fa9e6c8e92b2bdecd6b73869e67a07bfbde969936f921123d4c3e
```

This is similar to what we do in the [ci-build  workflow](https://github.com/star-bnl/star-sw/blob/cb94f7c8a92f018d54956709fb18382767532ba0/.github/workflows/ci-build.yml)

https://github.com/star-bnl/star-sw/blob/cb94f7c8a92f018d54956709fb18382767532ba0/.github/workflows/ci-build.yml#L17
https://github.com/star-bnl/star-sw/blob/cb94f7c8a92f018d54956709fb18382767532ba0/.github/workflows/ci-build.yml#L40

Nevertheless, the option for pulling by the latest tag should be restored

**Comment by R-Witt** [comment]
Workaround works for me.

**Comment by plexoos** [comment]
Thanks for confirming Richard. After pulling the image you may want to rename it in order to avoid the need to append that long hash string locally, e.g.

```bash
docker tag ghcr.io/star-bnl/star-sw-root5-base@sha256:4bed8a8b729fa9e6c8e92b2bdecd6b73869e67a07bfbde969936f921123d4c3e ghcr.io/star-bnl/star-sw-root5-base:latest
```

**Comment by veprbl** [comment]
Should not reappear with #197 included (perhaps still needs a backport to "active" release tags?)
