### ISSUE TITLE
Replacing sys/types.h with stdint.h

### ISSUE THREAD

**Issue by veprbl** [star-bnl/star-sw#213]
This is a tracking issue to replace non-standard types with types defined in the ISO C and C++ standards. Specifically, the following:

 - u_char, u_short, u_int -> uint8_t, uint16_t, uint32_t
 - ushort, uint, ulong -> unsigned short, unsigned int, unsigned long

The ultimate goal is to get rid of unnecessary includes of sys/types.h. This will help with ROOT5 being incompatible with the newest versions of libc (see https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/science/misc/root/purify_include_paths_root5.patch for an alternative solution).

 - [x] StRoot/Stv* (#211)
 - [x] StRoot/StTriggerUtilities (#212)
 - [x] StRoot/StSpinPool (#224)
 - [ ] StRoot/RTS (#225)
 - [ ] OnlTools (#225)
 - [ ] StRoot/St{,E}Emc*
 - [ ] StRoot/StDb*
 - [ ] StRoot/StDaqLib, StRoot/StDAQMaker
 - [x] StRoot/StGenericVertexMaker
 - [x] #234
 - [x] Disable _BSD_SOURCE?

**Comment by plexoos** [comment]
I don't think we have any _BSD_SOURCE in the code

**Comment by veprbl** [comment]
I don't remember what I was thinking, but it is probably controlled via other settings implemented in libc's. In any case, this can't be done unless we get rid of using that functionality first, which I don't think is going to happen at this point (we are blocked on having Jeff do the work on VxWorks bits).

**Comment by plexoos** [comment]
#443 should take care of the `StRoot/StGenericVertexMaker` bullet

**Comment by fgeurts** [comment]
Hi @veprbl and @plexoos,
Is this issue still tracking the non-standard type replacements? It hasn't been updated in a couple of years. Should we leave it open, assign to others, or has this been addressed and we should close it. Please advise.

**Comment by veprbl** [comment]
We weren't able to complete this migration fully. This is not a strict requirement for ROOT6-based builds. Let's close.
