### ISSUE TITLE
st_fwd crashing in StFcsPi0FinderForECal after PR #291

### ISSUE THREAD

**Issue by genevb** [star-bnl/star-sw#297]
It appears that every st_fwd stream file produced in DEV for FastOffline since PR #291 was merged is seg faulting. The log files from FastOffline all show lines like this:
```
Start using StFcsPi0FinderForECal
current event:2
StMaker:FATAL - TUnixSystem::DispatchSignals : segmentation violation
```
(though it does not always appear to be event 2; sometimes it is event 0 or 1, etc.)

-Gene

**Comment by genevb** [comment]
BFC chain to run:

    pp2022,StiCA,BEmcChkStat,epdhit,-hitfilt,-evout,-fcsCluster,-fcsPoint

I don't have any st_fwd files on disk to offer for a test, but maybe @akioogawa has one. The st_physics files are being processed just fine.

-Gene

**Comment by genevb** [comment]
These are probably not the issue as they occur in Init() and Finish(), instead of Make() where the "current event" is printed....

I saw the second line below was added in #291 to StFcsPi0FinderForEcal.cxx, which seems like it should come _after_ the check on the pointer being non-zero.

    mFcsDb = static_cast<StFcsDb*>(GetDataSet("fcsDb"));
    mFcsDb->setDbAccess(0);
    if (!mFcsDb) {

Another questionable spot was the addition of:

    TFile* MyFile = new TFile(fn, "RECREATE");
    ...
    MyFile->Close();

so the MyFile pointer is used without a test for it being non-zero. Again, these aren't likely the issue, but should also be corrected, I believe.

-Gene

**Comment by akioogawa** [comment]
Okey. My mistake. Those 2 are fixed before but somehow came back in with this PR. Is there easy way to revert back StFcsPi0FinderForEcal.cxx only from this commit?

**Comment by akioogawa** [comment]
Running StFcsPi0FinderForEcal does not make any sense when fcsCluster is off. Can you drop it until Mudst issue with StFcsCluster reading fixed and we put back fcsCluster?

**Comment by akioogawa** [comment]
Getting st_fwd daq file for debugging.

**Comment by plexoos** [comment]
Hm... How can anything official crash due to a problem in `StRoot/StSpinPool/StFcsPi0FinderForEcal/StFcsPi0FinderForEcal.cxx`? According to this page https://www.star.bnl.gov/public/comp/prod/Sanity/AutoBuild.html StSpinPool is excluded from the build

**Comment by akioogawa** [comment]
It's fastoffline, not real production.

**Comment by akioogawa** [comment]
I'm not sure why this is related to #297???

**Comment by plexoos** [comment]
> It's fastoffline, not real production.

Does it imply that fastoffline is not using `dev` libraries built from the `main` branch?

**Comment by akioogawa** [comment]
Please see #299
