### ISSUE TITLE
root4star crashes in StTofUtil/StTofrGeometry on 2008 data

### ISSUE THREAD

**Issue by plexoos** [star-bnl/star-sw#425]
**Describe the bug**

root4star segfaults on test 20. The log file from the failed test in #415 is at https://github.com/star-bnl/star-sw/actions/runs/3339378794/jobs/5530154347

```
Program received signal SIGSEGV, Segmentation fault.
StTofrGeometry::InitFromStar (this=this@entry=0xb999cd0, starHall=starHall@entry=0xbc38220) at .sl79_gcc485/OBJ/StRoot/StTofUtil/StTofrGeometry.cxx:1290
1290        if ( trayVolume->GetListSize() ) {
```

Test 20 parameters are:
https://github.com/star-bnl/star-sw/blob/10774c59a608d93191beb3d37392d39812b48022/tests/joblist.json#L182-L190

**To Reproduce**

```sh
root4star -b -q -l 'bfc.C(40, "DbV20080712,P2008,ITTF,OSpaceZ2,OGridLeak3D,beamLine", "/star/rcf/test/daq/2007/352/st_physics_8352025_raw_1030011.daq")'
```

**Expected behavior**

No segmentation fault

**Comment by starsdong** [comment]
Dmitri, I am curious whether this issue has been resolved. I tried the test macro you provided and the code ran fine without seg fault?
/star/u/dongx/pwg/Git/20221206/test.log

**Comment by plexoos** [comment]
Thanks for checking Xin. I don't know what might have fixed this issue but let me try to enable it and see.

**Comment by plexoos** [comment]
The test still does not go through, see #459

**Comment by fgeurts** [comment]
Hi @plexoos, 
I also just ran the macro and did not see a seg.fault (running in SL23c). Does the test still fail?

**Comment by fgeurts** [comment]
Propose to close this ticket. Not reproducible. TOFr code for 2008 d+Au is not needed.
