### ISSUE TITLE
StarVMC/StarGeometry doesn't compile on main branch

### ISSUE THREAD

**Issue by veprbl** [star-bnl/star-sw#45]
### Steps to reproduce

On RACF run:
```bash
git clone https://github.com/star-bnl/star-sw.git
cd star-sw
git checkout f7935bbbca1c9e9c69931bb5167ca9767be72807
env -i \
  PATH=$PWD/mgr:$PATH \
  QTDIR=/usr/lib64/qt-3.3 QTINC=/usr/lib64/qt-3.3/include \
  QTLIB=/usr/lib64/qt-3.3/lib CERN_LEVEL=pro \
  CERN=/cern CERN_ROOT=/cern/pro \
  ROOTSYS=/afs/rhic.bnl.gov/star/ROOT/5.34.38/.sl73_gcc485/rootdeb \
  ROOT=/afs/rhic.bnl.gov/star/ROOT \
  ROOT_LEVEL=5.34.38 \
  STAR_SYS=x8664_sl7 \
  STAR_HOST_SYS=sl73_gcc485 \
  OPTSTAR=/opt/star/sl73_gcc485 \
  XOPTSTAR=/afs/rhic.bnl.gov/opt/star/sl73_gcc485 \
  STAR_ROOT=/afs/rhic.bnl.gov/star \
  STAR=/nowhere \
  sh -c '. $ROOTSYS/bin/thisroot.sh; exec cons %StShadowMaker'
```

Observe:
```
Install StarVMC/StarGeometry/BtofConfig.cxx as .sl73_gcc485/obj/StarVMC/StarGeometry/BtofConfig.cxx
g++ -m32 -fPIC -pipe -Wall -Woverloaded-virtual -std=c++0x -Wno-long-long -pthread -g -Dsl73_gcc485 -D__ROOT__ -DNEW_DAQ_READER -I. -IStRoot -I.sl73_gcc485/include -I/afs/rhic.bnl.gov/star/ROOT/5.34.38/.sl73_gcc485/rootdeb/include -c .sl73_gcc485/obj/StarVMC/StarGeometry/BtofConfig.cxx -o .sl73_gcc485/obj/StarVMC/StarGeometry/BtofConfig.o
In file included from .sl73_gcc485/obj/StarVMC/StarGeometry/BtofConfig.cxx:1:0:
./StarVMC/StarGeometry/BtofConfig.h:3:45: fatal error: StarVMC/StarGeometry/BtofGeo1.h: No such file or directory # include "StarVMC/StarGeometry/BtofGeo1.h"                                              ^
compilation terminated.
cons: *** [.sl73_gcc485/obj/StarVMC/StarGeometry/BtofConfig.o] Error 1
cons: errors constructing .sl73_gcc485/obj/StarVMC/StarGeometry/BtofConfig.o
```

### Expected result

Everything compiles without errors

cc @klendathu2k

**Comment by klendathu2k** [comment]
First of all, for your first build from a freshly checked-out repository I recommend building the geometry sources...
$ cons +StarVMC/Geometry

That being said, there is an issue here.  Working from the current head and the standard STAR environment / login...  I am able to demonstrate misbehavior...

$ git clone https://github.com/star-bnl/star-sw.git
$ cd star-sw/
$ stardev
$ cons +StarVMC/Geometry

... cons does not do the agml --> cxx conversion step.  So the geometry build is incomplete (and cons may try to  install codes from the $STAR library directory).

Workaround is to set the star library to "NONE" before building the geometry...

Start from a clean directory...

clone, then 
$ cd star-sw
$ starver NONE # and ignore the error...
$ cons +StarVMC/Geometry

This should take some time.  Take a walk.  Drink some coffee.  Read War and Peace.  Etc... Afterwards, compile against DEV... (or some appropriate library...)

$ stardev 

$ cons +StarVMC/StarGeometry
$ cons +StarVMC/xgeometry
(or just)
$ cons

----------------------------

Solution will involve convincing cons to ignore the code in $STAR when deciding whether or not to build the local geometry code...

**Comment by plexoos** [comment]
Does anyone know the official way of compiling all libraries with cons? With some trial and error I came up with the following sequence that seems to work in the container but it is not pretty:

https://github.com/star-bnl/star-sw/blob/f7935bbbca1c9e9c69931bb5167ca9767be72807/Dockerfile#L94-L101

**Comment by veprbl** [comment]
> Solution will involve convincing cons to ignore the code in $STAR when deciding whether or not to build the local geometry code...

I'm not sure I follow. The issue is observed when I try to bootstrap star-sw with `STAR=/nowhere`, which is done so that build does not pick up the existing headers. I suppose, the solution will be to convince cons to compile BtofGeo1.h (from xml?) before compiling the BtofConfig.cxx.

**Comment by klendathu2k** [comment]
Hi Dmitry,

The workaround (starver NONE, & etc...) should allow you to compile the 
code.
Please let me know whether this works for you or not.


For a complete solution (to close the issue) we (S&C) will need to 
modify cons
so that the dependencies are correct, and cons actually builds the c++ 
code from
the XML sources.  It may be sufficient to modify cons to ignore the 
presence of the
build products under $STAR.  But cons is written in perl, and 
understanding it
may cause insanity.  Or at least insomnia.  Will look at later.

Cheers,
Jason

**Comment by veprbl** [comment]
> Does anyone know the official way of compiling all libraries with cons?

Could be this https://github.com/star-bnl/star-sw/blob/main/mgr/CmpSL

**Comment by klendathu2k** [comment]
I believe that comments/documentation in mgr/cons line 5920 discusses this very issue...

(Not "how to build STAR libraries... but rather the build issue).
