### ISSUE TITLE
PR #500 broke numerous DEV nightly tests

### ISSUE THREAD

**Issue by genevb** [star-bnl/star-sw#509]
PR #500 was merged on Friday, March 17. Since then, the below-listed DEV nightly tests at SDCC have been failing 3 times in a row  with the following error:

StdEdxY2Maker:WARN  - Validity:19950101/0 -----   20151215/0
StChain:WARN  - StDbSql::QueryDb(table,time) line=439 TpcPadCorrectionMDC  has No data for query
root4star: .sl73_gcc485/OBJ/StRoot/StDetectorDbMaker/StDetectorDbChairs.cxx:473: static St_TpcPadCorrectionMDC* St_TpcPadCorrectionMDC::instance(): Assertion `table' failed.

One can look at the log files in any of these directories (use either  the`Sat`, `Sun`, or `Mon` iterations of these tests, or `Tue` by tomorrow):

/star/rcf/test/dev/daq_sl302.ittf/Sun/year_2004/AuAuMinBias
/star/rcf/test/dev/daq_sl302.ittf/Sun/year_2007/2007ProductionMinBias
/star/rcf/test/dev/daq_sl302.ittf/Sun/year_2008/production_dAu2008
/star/rcf/test/dev/daq_sl302.ittf/Sun/year_2003/dAuMinBias
/star/rcf/test/dev/daq_sl302.ittf_opt/Sun/year_2003/dAuMinBias
/star/rcf/test/dev/daq_sl302.ittf_opt/Sun/year_2004/AuAu_prodHigh
/star/rcf/test/dev/daq_sl302.ittf_opt/Sun/year_2004/AuAu_prodLow
/star/rcf/test/dev/daq_sl302.ittf_opt/Sun/year_2004/prodPP
/star/rcf/test/dev/daq_sl302.ittf_opt/Sun/year_2007/2007Production
/star/rcf/test/dev/daq_sl302.ittf_opt/Sun/year_2007/2007ProductionMinBias
/star/rcf/test/dev/daq_sl302.ittf_opt/Sun/year_2008/ppProduction2008
/star/rcf/test/dev/daq_sl302.ittf_opt/Sun/year_2008/production_dAu2008
 /star/rcf/test/dev/daq_sl302.ittf/Sun/year_2010/auau11_embed
/star/rcf/test/dev/daq_sl302.ittf/Sun/year_2010/auau39_embed
/star/rcf/test/dev/daq_sl302.ittf/Sun/year_2010/auau7_embed
/star/rcf/test/dev/daq_sl302.ittf/Sun/year_2011/AuAu200_embed
/star/rcf/test/dev/daq_sl302.ittf/Sun/year_2009/pp200_embed
/star/rcf/test/dev/daq_sl302.ittf_opt/Sun/year_2004/AuAuMinBias
/star/rcf/test/dev/daq_sl302.ittf/Sun/year_2005/CuCu200_embedTpc
/star/rcf/test/dev/daq_sl302.ittf/Sun/year_2007/auau200_embedTpcSvtSsd
/star/rcf/test/dev/daq_sl302.ittf/Sun/year_2010/auau200_embed
/star/rcf/test/dev/daq_sl302.ittf/Sun/year_2011/pp500_embed
/star/rcf/test/dev/daq_sl302.ittf/Sun/year_2012/pp200_embed
/star/rcf/test/dev/daq_sl302.ittf/Sun/year_2005/CuCu200_embedTpcSvtSsd
/star/rcf/test/dev/daq_sl302.ittf/Sun/year_2012/UU193_embed

-Gene

**Comment by starsdong** [comment]
Hi Gene, comments from Yuri:
"I have reset entryTime from “2023-03-13 23:45:59“ to “2000-01-01 00:00:00” for rows with beginTime =  “2000-01-01 00:00:01’, Now jobs with  DbV time stamp should  work for dataset without  TpcPadCorrectionMDC."
Could you give another try to see this issue is resolved? Thanks

**Comment by genevb** [comment]
> Could you give another try to see this issue is resolved? Thanks

I'll report on tonight's nightly tests in the morning.

-Gene

**Comment by genevb** [comment]
Of the jobs that have finished today (only 4 of the 25 listed consistently crashing jobs haven't finished yet), none have crashed with this error. So it appears to be resolved. Closing this issue.
