### ISSUE TITLE
TTable not found when compiling for ROOT6 with spack environment 0.3.0

### ISSUE THREAD

**Issue by genevb** [star-bnl/star-sw#597]
I'm trying to compile SL23x on AFS with ROOT 6.24.06 with spack environment 0.3.0 from PR #595 , but the compilation isn't finding TTable.

setup 64bits
setenv STAR `pwd`
starver SL23x config/v0.3.0-rhel7-root6.24.06
cons 

...

g++ -g -m64 -Wl,-export-dynamic -Wl,-noinhibit-exec,-Bdynamic .sl73_x8664_gcc485/obj/asps/rexe/MAIN_rmain.o .sl73_x8664_gcc485/obj/asps/rexe/df.o .sl73_x8664_gcc485/obj/asps/rexe/root4star_Cint.o .sl73_x8664_gcc485/obj/asps/rexe/TGeant3/StarMC.o .sl73_x8664_gcc485/obj/asps/rexe/TGeant3/TGiant3.o .sl73_x8664_gcc485/obj/asps/rexe/TGeant3/galicef.o .sl73_x8664_gcc485/obj/asps/rexe/TGeant3/gcadd.o .sl73_x8664_gcc485/obj/asps/rexe/TGeant3/gcomad.o -L/cvmfs/star.sdcc.bnl.gov/star-spack/spack/opt/spack/linux-rhel7-x86_64/gcc-4.8.5/root-6.24.06-ynrr5dh6ahvh4gpwx5uv3jmzhofxng4x/lib -L.sl73_x8664_gcc485/lib -L/afs/rhic.bnl.gov/star/packages/SL23x/.sl73_x8664_gcc485/lib -L/cvmfs/star.sdcc.bnl.gov/star-spack/spack/opt/spack/linux-rhel7-x86_64/gcc-4.8.5/root-6.24.06-ynrr5dh6ahvh4gpwx5uv3jmzhofxng4x/lib -L/cvmfs/star.sdcc.bnl.gov/star-spack/spack/opt/spack/linux-rhel7-x86_64/gcc-4.8.5/mysql-5.6.43-dxccl67cjodink5q5l2qdvydds7x4ynr/lib -L/opt/star/sl73_x8664_gcc485/qt4/lib -L/opt/star/sl73_x8664_gcc485/lib -L/cvmfs/star.sdcc.bnl.gov/star-spack/spack/opt/spack/linux-rhel7-x86_64/gcc-4.8.5/mysql-5.6.43-dxccl67cjodink5q5l2qdvydds7x4ynr/lib -Wl,--whole-archive -Wl,-Bstatic -Wl,-z -Wl,muldefs -lstarsim -Wl,--no-whole-archive -Wl,-Bdynamic -lCore -lImt -lRIO -lNet -lHist -lGraf -lGraf3d -lGpad -lROOTVecOps -lTree -lTreePlayer -lRint -lPostscript -lMatrix -lPhysics -lMathCore -lThread -lMultiProc -lROOTDataFrame -lGeom -lTable -lgeant321 -lgcalor /cern64/pro/lib/libpawlib.a /cern64/pro/lib/liblapack3.a /cern64/pro/lib/libblas.a /cern64/pro/lib/libpacklib_noshift.a /cern64/pro/lib/libgraflib.a /cern64/pro/lib/libgrafX11.a /cern64/pro/lib/libpacklib_noshift.a /cern64/pro/lib/libmathlib.a /cern64/pro/lib/libkernlib_noshift.a -L/usr/X11R6/lib -lX11 -lnsl -lcrypt -ldl -lmysqlclient -lpthread -lm -ldl -lgfortran -lquadmath -L/usr/X11R6/lib64 -lXt -lXpm -lX11 -lm -ldl -lrt -rdynamic -pthread -o .sl73_x8664_gcc485/obj/asps/rexe/root4star
/usr/bin/ld: cannot find -lTable
collect2: error: ld returned 1 exit status
cons: *** [.sl73_x8664_gcc485/obj/asps/rexe/root4star] Error 1
cons: errors constructing .sl73_x8664_gcc485/obj/asps/rexe/root4star

-Gene

**Comment by genevb** [comment]
Perhaps it's a matter of changing the order of compilation? I don't see that Table.o or Table.so have yet been compiled at the moment that it's trying to compile root4star. Suggestions on something to try are welcome.

-Gene

**Comment by plexoos** [comment]
I haven't tried 6.24.06 but the following setup for 6.16.00 followed by 'cons' worked for me:

```
setup 64b                                                                                                                   
setenv NODEBUG yes                                                                                                          
unsetenv _LMFILES_*                                                                                                         
module purge                                                                                                                
module use   /cvmfs/star.sdcc.bnl.gov/star-spack/spack/share/spack/modules/linux-rhel7-x86_64/                              
module load star-env-0.3.0-root-6.16.00                                                                                     
setenv STAR $PWD                                                                                                            
setenv STAR_LIB ${STAR}/.${STAR_HOST_SYS}/LIB                                                                               
setenv STAR_BIN ${STAR}/.${STAR_HOST_SYS}/BIN                                                                               
setenv PATH ${STAR_BIN}:${STAR}/mgr:${PATH}                                                                                 
setenv LD_LIBRARY_PATH ${STAR_LIB}:${LD_LIBRARY_PATH}                                                                       
setenv ROOT_INCLUDE_PATH $STAR/.${STAR_HOST_SYS}/include:${ROOT_INCLUDE_PATH}   
```

**Comment by plexoos** [comment]
Unlikely related to this issue, but I noticed something else when loading on interactive nodes https://github.com/star-bnl/star-spack/issues/42

**Comment by genevb** [comment]
Just a note of status on this issue:

- I have not re-tested compiling for ROOT 6.24.06 since the time I opened this issue, but...
- Just as Dmitri noted, compiling for ROOT 6.16.00 worked OK. 

I'll come back to trying ROOT 6.24.06 as some point, but for now it isn't urgent with 6.16.00 working.

**Comment by genevb** [comment]
Resolved somewhere along the line: we now have ROOT 6.24.06 in SL23x.
