### ISSUE TITLE
Compiler error in StarVMC due to missing TPainter3dAlgorithms.h in ROOT 6.24.06

### ISSUE THREAD

**Issue by plexoos** [star-bnl/star-sw#600]
g++ -m64 -fPIC -pipe -Wall -Woverloaded-virtual -std=c++0x -Wno-long-long -pthread -O2 -g -falign-loops -falign-jumps -falign-functions -Dsl73_x8664_gcc485 -D__ROOT__ -DNEW_DAQ_READER -I. -IStRoot -I.sl73_x8664_gcc485/include -I/cvmfs/star.sdcc.bnl.gov/star-spack/spack/opt/spack/linux-rhel7-x86_64/gcc-4.8.5/root-6.24.06-ynrr5dh6ahvh4gpwx5uv3jmzhofxng4x/include -c .sl73_x8664_gcc485/OBJ/StarVMC/GeoTestMaker/StTProfile2D.cxx -o .sl73_x8664_gcc485/OBJ/StarVMC/GeoTestMaker/StTProfile2D.o
.sl73_x8664_gcc485/OBJ/StarVMC/GeoTestMaker/StTProfile2D.cxx:209:34: fatal error: TPainter3dAlgorithms.h: No such file or directory
 #include "TPainter3dAlgorithms.h"
                                  ^
compilation terminated.
cons: *** [.sl73_x8664_gcc485/OBJ/StarVMC/GeoTestMaker/StTProfile2D.o] Error 1

**Comment by klendathu2k** [comment]
I believe that GeoTestMaker can be removed.  (It may be that "Stv" depends on it, but nothing that we need to keep around at this point.)  Will investigate.

Have a draft PR#603... waiting for checks to pass.

**Comment by plexoos** [comment]
Resolved by removing unused StarVMC/GeoTestMaker in #603
