### ISSUE TITLE
starver dev unable to locate module file

### ISSUE THREAD

**Issue by jdbrice** [star-bnl/star-sw#604]
**Describe the bug**

`starver dev` reports
ModuleCmd_Load.c(213):ERROR:105: Unable to locate a modulefile for 'star-env-0.2.3-root-5.34.38'

**To Reproduce**
```
[rcas6009] ~/work/ssw/fwd-dev/> starver dev
ModuleCmd_Load.c(213):ERROR:105: Unable to locate a modulefile for 'star-env-0.2.3-root-5.34.38'

[rcas6009] ~/work/ssw/fwd-dev/> starver dev config/v0.3.0-rhel7-root5.34.38.config
ModuleCmd_Load.c(213):ERROR:105: Unable to locate a modulefile for 'star-env-0.2.3-root-5.34.38'
```

**Expected behavior**

no error message.

I am guessing this is related to the recent upgrade from 0.2.3 to 0.3

**Comment by genevb** [comment]
Hi, Daniel.

From what I can tell, version 0.2.3 was removed from CVMFS before DEV was rebuilt, so you were not alone in seeing the error.

I understand from Dmitri that he has updated CVMFS and that it should now build fine. So I started the rebuild process this afternoon and have found:
1) 64-bit builds fine
2) 32-bit fails to build StFwdTrackMaker due to failure to find `GenFit/GFRaveVertexFactory.h`

So, I can release DEV within an hour or two with StFwdTrackMaker available only in 64-bit, but not available in 32-bit. Is that acceptable for now (until Dmitri helps get GenFit working again in 32-bit)?

-Gene

**Comment by plexoos** [comment]
Yes, https://github.com/star-bnl/star-sw/pull/601 will fix this issue

**Comment by plexoos** [comment]
> until Dmitri helps get GenFit working again in 32-bit

Please open another issue with a how-to reproduce instructions. As of now I don't see any issues with GenFit. I was able to compile both 32 and 64-bit libs using `star-env-0.3.0-root-5.34.38`. Here is the setup I used:

```
setup 32b
#setup 64b
setenv NODEBUG yes
unsetenv _LMFILES_*
module purge
module use   /cvmfs/star.sdcc.bnl.gov/star-spack/spack/share/spack/modules/linux-rhel7-x86/
#module use   /cvmfs/star.sdcc.bnl.gov/star-spack/spack/share/spack/modules/linux-rhel7-x86_64/
module load star-env-0.3.0-root-5.34.38
#module load star-env-0.3.0-root-6.16.00
#module load star-env-0.3.0-root-6.24.06
setenv STAR $PWD
setenv STAR_LIB ${STAR}/.${STAR_HOST_SYS}/LIB
setenv STAR_BIN ${STAR}/.${STAR_HOST_SYS}/BIN
setenv PATH ${STAR_BIN}:${STAR}/mgr:${PATH}
setenv LD_LIBRARY_PATH ${STAR_LIB}:${LD_LIBRARY_PATH}
setenv ROOT_INCLUDE_PATH $STAR/.${STAR_HOST_SYS}/include:${ROOT_INCLUDE_PATH}
```

**Comment by plexoos** [comment]
In case it is not clear, by setting the environment the way I set it up, I mimic the environment for building star-sw from scratch as for an official binary release. In his case, only files in the local directory are used.

**Comment by genevb** [comment]
Re-trying 32-bit this evening compiled fine. Whatever kept it from compiling earlier seems to have resolved itself.

32-bit, 64-bit, non-optimized, optimized, all built OK.  DEV released. Give it a try, Daniel.

-Gene

**Comment by plexoos** [comment]
I rebuilt the 0.3.0 environments over the weekend to eliminate any interference with the removed 0.2.3 in /cvmfs/star.

Compiling 32/64-bit libs or star-sw against those packages (in a private directory) worked for me in the both ROOT5 and ROOT6.16 environments.

If there are any issues, please let me know.

**Comment by genevb** [comment]
I also re-compiled DEV today with the latest star-spack from Dmitri in place. I had no issues either. Hopefully all is well.
