### ISSUE TITLE
StTriggerData2022 version number wasn't incremented

### ISSUE THREAD

**Issue by genevb** [star-bnl/star-sw#609]
A user sent me a log file of processing a MuDst from FastOffline of Run 22 data for which running his macro produced the following error in SL23d:

    The StreamerInfo of class StTriggerData2022 read from file /star/data100/reco/production_pp500_2022/ReversedFullField/dev/2022/078/23078044/st_physics_23078044_raw_3500050.MuDst.root
     has the same version (=1) as the active class but a different checksum.
     You should update the version to ClassDef(StTriggerData2022,2).
     Do not try to write objects with the current class definition,
     the files will not be readable.

I spotted this update, which didn't include a ClassDef incrementation and was made _after_ Run 22 finished: #450 

I asked the user to run their macro in SL22c, which was from before that update to StTriggerData2022.h, and the error went away. So it probably should have been incremented.

-Gene

**Comment by akioogawa** [comment]
I'm puzzled. #450 did add non-IO variables with //!, thus won't need version change?

**Comment by genevb** [comment]
I see your point, @akioogawa, and I don't have an explanation. I believe you are correct that changes to non-streamed (or "transient") members don't require a streamer version change, so in principle this shouldn't be needed. I did not provide a "how-to-reproduce" for this as the same user is still having other problems with their macro and opened Issue #611. I don't know if anyone else is reading Run 22 MuDsts and seeing the same messages or not, but in principle it should be straightforward to test whether incrementing the version number truly resolves it.

**Comment by plexoos** [comment]
Fixed in #612
