### ISSUE TITLE
Revisiting dependency on C++ boost 

### ISSUE THREAD

**Issue by plexoos** [star-bnl/star-sw#81]
As far as I can tell, the only package that depends on boost is [StRoot/StarGenerator/Kinematics](https://github.com/star-bnl/star-sw/tree/main/StRoot/StarGenerator/Kinematics). It includes the following header

https://github.com/star-bnl/star-sw/blob/cd4338393c9bb095f94e223bc673732275b2a74d/StRoot/StarGenerator/Kinematics/StarKinematics.cxx#L7

and makes use of `boost:split()`

https://github.com/star-bnl/star-sw/blob/cd4338393c9bb095f94e223bc673732275b2a74d/StRoot/StarGenerator/Kinematics/StarKinematics.cxx#L85

Although some version of boost is available on the farm nodes, it is not targeted as direct dependency by the current Spack environment. Since boost is missing from the environment StRoot/StarGenerator/Kinematics cannot be compiled and is excluded from the build

https://github.com/star-bnl/star-sw/blob/cd4338393c9bb095f94e223bc673732275b2a74d/docker/Dockerfile.root5#L121-L130

Installing the entire boost package for just a single function (`boost:split`) does not seem very practical... Would it make more sense to replace the call to `boost::split()` with a few lines of equivalent code?

@klendathu2k

**Comment by veprbl** [comment]
This should be an equivalent:

```c++
vector<string> split(const string &s, const string &sep_chars)
{ 
  string::size_type prev_pos = 0, pos = 0;
  vector<string> result;

  while ((pos = s.find_first_of(sep_chars, pos)) != string::npos) {
    result.push_back(s.substr(prev_pos, pos - prev_pos));
    pos += 1;
    prev_pos = pos;
  }
  result.push_back(s.substr(prev_pos));

  return result;
}

void test() {
  for(auto s : split("1,2 3, 5", ", ")) {
    std::cout << "\"" << s << "\"" << std::endl;
  }
}
```
